apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-cd-practica
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Andyn151/CI-CD_practica'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
